version: '2.1'

services:
  pxt-container-stm32-iot-node:
    image: pxt-container-stm32-iot-node
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3232:3232
      - 3233:3233
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js